In [1]:
from smawk_edu import smawk_arr_edu
import numpy as np

In [2]:
s = """25 21 13 10 20 13 19 35 37 41 58 66 82 99 124 133 156 178
42 35 26 20 29 21 25 37 36 39 56 64 76 91 116 125 146 164
57 48 35 28 33 24 28 40 37 37 54 61 72 83 107 113 131 146
78 65 51 42 44 35 38 48 42 42 55 61 70 80 100 106 120 135
90 76 58 48 49 39 42 48 39 35 47 51 56 63 80 86 97 110
103 85 67 56 55 44 44 49 39 33 41 44 49 56 71 75 84 96
123 105 86 75 73 59 57 62 51 44 50 52 55 59 72 74 80 92
142 123 100 86 82 65 61 62 50 43 47 45 46 46 58 59 65 73
151 130 104 88 80 59 52 49 37 29 29 24 23 20 28 25 31 39"""
arr0 = np.array([list(map(int, s2.split(" "))) for s2 in s.splitlines()])

In [6]:
result = smawk_arr_edu(arr0)

begin_reduce
[0 1 2 3 4 5 6 7 8] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 25  21  13  10  20  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [ 42  35  26  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [ 57  48  35  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [ 78  65  51  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [ 90  76  58  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [103  85  67  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [123 105  86  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [142 123 100  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [151 130 104  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 0 col 0 with col 0 (25 vs 25)
[[  0  21  13  10  20  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [ 42  35  26  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [ 57  48  35  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [ 78  65  51  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [ 90  76  58  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [103  85  67  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [123 105  86  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [142 123 100  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [151 130 104  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 1 col 0 with col 1 (42 vs 35)
comparing row 0 col 0 with col 1 (25 vs 21)
[[  0  21  13  10  20  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [  0  35  26  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [  0  48  35  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0  65  51  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0  76  58  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0  85  67  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0 105  86  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0 123 100  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0 130 104  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 0 col 1 with col 2 (21 vs 13)
[[  0   0  13  10  20  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [  0   0  26  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [  0   0  35  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0   0  51  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0  58  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0  67  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0  86  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0 100  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0 104  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 0 col 2 with col 3 (13 vs 10)
[[  0   0   0  10  20  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 0 col 3 with col 4 (10 vs 20)
[[  0   0   0  10   0  13  19  35  37  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20  29  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28  33  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42  44  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48  49  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56  55  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75  73  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86  82  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88  80  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 1 col 4 with col 5 (29 vs 21)
comparing row 0 col 3 with col 5 (10 vs 13)
[[  0   0   0  10   0   0  19  35  37  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21  25  37  36  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 1 col 5 with col 6 (21 vs 25)
[[  0   0   0  10   0   0   0  35  37  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0  37  36  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28  40  37  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 2 col 6 with col 7 (28 vs 40)
[[  0   0   0  10   0   0   0   0  37  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0  36  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0  37  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38  48  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42  48  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44  49  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57  62  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61  62  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52  49  37  29  29  24  23  20  28  25  31  39]]
comparing row 3 col 7 with col 8 (48 vs 42)
comparing row 2 col 6 with col 8 (28 vs 37)
[[  0   0   0  10   0   0   0   0   0  41  58  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0  39  56  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0  37  54  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42  42  55  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 3 col 8 with col 9 (42 vs 42)
[[  0   0   0  10   0   0   0   0   0   0  58  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0  56  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0  54  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0  55  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35  47  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 4 col 9 with col 10 (35 vs 47)
[[  0   0   0  10   0   0   0   0   0   0   0  66  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0  64  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0  61  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0  61  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0  51  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41  44  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 5 col 10 with col 11 (41 vs 44)
[[  0   0   0  10   0   0   0   0   0   0   0   0  82  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0  76  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0  72  83 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0  70  80 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0  56  63  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0  49  56  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52  55  59  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 6 col 11 with col 12 (52 vs 55)
[[  0   0   0  10   0   0   0   0   0   0   0   0   0  99 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0   0  91 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0   0  83 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0   0  80 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0   0  63  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0   0  56  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52   0  59  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46  46  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 7 col 12 with col 13 (46 vs 46)
[[  0   0   0  10   0   0   0   0   0   0   0   0   0   0 124 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0   0   0 116 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0   0   0 107 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0   0   0 100 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0   0   0  80  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0   0   0  71  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52   0   0  72  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46   0  58  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20  28  25  31  39]]
comparing row 8 col 13 with col 14 (20 vs 28)
[[  0   0   0  10   0   0   0   0   0   0   0   0   0   0   0 133 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0   0   0   0 125 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0   0   0   0 113 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0   0   0   0 106 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0   0   0   0  86  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0   0   0   0  75  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52   0   0   0  74  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46   0   0  59  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20   0  25  31  39]]
comparing row 8 col 13 with col 15 (20 vs 25)
[[  0   0   0  10   0   0   0   0   0   0   0   0   0   0   0   0 156 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0   0   0   0   0 146 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0   0   0   0   0 131 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0   0   0   0   0 120 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0   0   0   0   0  97 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0   0   0   0   0  84  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52   0   0   0   0  80  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46   0   0   0  65  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20   0   0  31  39]]
comparing row 8 col 13 with col 16 (20 vs 31)
[[  0   0   0  10   0   0   0   0   0   0   0   0   0   0   0   0   0 178]
 [  0   0   0  20   0  21   0   0   0   0   0   0   0   0   0   0   0 164]
 [  0   0   0  28   0  24  28   0   0   0   0   0   0   0   0   0   0 146]
 [  0   0   0  42   0  35  38   0  42   0   0   0   0   0   0   0   0 135]
 [  0   0   0  48   0  39  42   0  39  35   0   0   0   0   0   0   0 110]
 [  0   0   0  56   0  44  44   0  39  33  41   0   0   0   0   0   0  96]
 [  0   0   0  75   0  59  57   0  51  44  50  52   0   0   0   0   0  92]
 [  0   0   0  86   0  65  61   0  50  43  47  45  46   0   0   0   0  73]
 [  0   0   0  88   0  59  52   0  37  29  29  24  23  20   0   0   0  39]]
comparing row 8 col 13 with col 17 (20 vs 39)
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0 21  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24 28  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 42  0 35 38  0 42  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 48  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0 56  0 44 44  0 39 33 41  0  0  0  0  0  0  0]
 [ 0  0  0 75  0 59 57  0 51 44 50 52  0  0  0  0  0  0]
 [ 0  0  0 86  0 65 61  0 50 43 47 45 46  0  0  0  0  0]
 [ 0  0  0 88  0 59 52  0 37 29 29 24 23 20  0  0  0  0]]
end_reduce
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0 21  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24 28  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 42  0 35 38  0 42  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 48  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0 56  0 44 44  0 39 33 41  0  0  0  0  0  0  0]
 [ 0  0  0 75  0 59 57  0 51 44 50 52  0  0  0  0  0  0]
 [ 0  0  0 86  0 65 61  0 50 43 47 45 46  0  0  0  0  0]
 [ 0  0  0 88  0 59 52  0 37 29 29 24 23 20  0  0  0  0]]
reduce_result [ 3  5  6  8  9 10 11 12 13]
[1 3 5 7] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
begin_reduce
[1 3 5 7] [ 3  5  6  8  9 10 11 12 13]
[[20 21  0  0  0  0  0  0  0]
 [42 35 38 42  0  0  0  0  0]
 [56 44 44 39 33 41  0  0  0]
 [86 65 61 50 43 47 45 46  0]]
comparing row 1 col 0 with col 3 (42 vs 20)
[[20 21  0  0  0  0  0  0  0]
 [42 35 38 42  0  0  0  0  0]
 [56 44 44 39 33 41  0  0  0]
 [86 65 61 50 43 47 45 46  0]]
comparing row 1 col 3 with col 5 (20 vs 21)
[[20  0  0  0  0  0  0  0  0]
 [42 35 38 42  0  0  0  0  0]
 [56 44 44 39 33 41  0  0  0]
 [86 65 61 50 43 47 45 46  0]]
comparing row 3 col 5 with col 6 (35 vs 38)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0 42  0  0  0  0  0]
 [56 44 44 39 33 41  0  0  0]
 [86 65 61 50 43 47 45 46  0]]
comparing row 5 col 6 with col 8 (44 vs 39)
comparing row 3 col 5 with col 8 (35 vs 42)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0 39 33 41  0  0  0]
 [86 65  0 50 43 47 45 46  0]]
comparing row 5 col 8 with col 9 (39 vs 33)
comparing row 3 col 5 with col 9 (35 vs 42)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0  0 33 41  0  0  0]
 [86 65  0  0 43 47 45 46  0]]
comparing row 5 col 9 with col 10 (33 vs 41)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0  0 33  0  0  0  0]
 [86 65  0  0 43 47 45 46  0]]
comparing row 7 col 10 with col 11 (47 vs 45)
comparing row 5 col 9 with col 11 (33 vs 44)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0  0 33  0  0  0  0]
 [86 65  0  0 43  0 45 46  0]]
comparing row 7 col 11 with col 12 (45 vs 46)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0  0 33  0  0  0  0]
 [86 65  0  0 43  0 45  0  0]]
comparing row 7 col 11 with col 13 (45 vs 46)
[[20  0  0  0  0  0  0  0  0]
 [42 35  0  0  0  0  0  0  0]
 [56 44  0  0 33  0  0  0  0]
 [86 65  0  0 43  0 45  0  0]]
end_reduce
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 42  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 48  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0 56  0 44  0  0  0 33  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0 59  0  0  0 44 50 52  0  0  0  0  0  0]
 [ 0  0  0 86  0 65  0  0  0 43  0 45  0  0  0  0  0  0]
 [ 0  0  0 88  0 59  0  0  0 29  0 24 23 20  0  0  0  0]]
reduce_result [ 3  5  9 11]
[3 7] [ 3  5  6  8  9 10 11 12 13]
begin_reduce
[3 7] [ 3  5  9 11]
[[42 35  0  0]
 [86 65 43 45]]
comparing row 3 col 0 with col 3 (78 vs 42)
[[42 35  0  0]
 [86 65 43 45]]
comparing row 3 col 3 with col 5 (42 vs 35)
[[ 0 35  0  0]
 [ 0 65 43 45]]
comparing row 3 col 5 with col 9 (35 vs 42)
[[ 0 35  0  0]
 [ 0 65 43 45]]
comparing row 7 col 9 with col 11 (43 vs 45)
[[ 0 35  0  0]
 [ 0 65 43  0]]
end_reduce
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0 33  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0 44 50  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 65  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0 29  0 24 23 20  0  0  0  0]]
reduce_result [5 9]
[7] [ 3  5  9 11]
begin_reduce
[7] [5 9]
[[65 43]]
comparing row 7 col 0 with col 5 (142 vs 65)
[[65 43]]
comparing row 7 col 5 with col 9 (65 vs 43)
[[ 0 43]]
end_reduce
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0 33  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0 44 50  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 29  0 24 23 20  0  0  0  0]]
reduce_result [9]
[] [5 9]
[3 3 0 5 0 0 0 9 0]
begin interpolate
5 5 9
comparing row 5 col 5 with col 9 (44 vs 33)
end_interpolate
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39 42  0 39 35  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 44 50  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 29  0 24 23 20  0  0  0  0]]
[3 3 0 5 0 9 0 9 0]
begin interpolate
2 3 5
comparing row 2 col 3 with col 5 (28 vs 24)
4 5 9
comparing row 4 col 5 with col 6 (39 vs 42)
comparing row 4 col 6 with col 8 (39 vs 39)
comparing row 4 col 8 with col 9 (39 vs 35)
6 9 9
8 9 13
comparing row 8 col 9 with col 10 (29 vs 29)
comparing row 8 col 10 with col 11 (29 vs 24)
comparing row 8 col 11 with col 12 (24 vs 23)
comparing row 8 col 12 with col 13 (23 vs 20)
end_interpolate
[[ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 35  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 44 50  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0]]

In [7]:
np.testing.assert_array_equal(result, np.argmin(arr0,axis=1))